### PR TITLE
Html branch

### PR DESCRIPTION
**Pull request by gchave77**
Please review updates to the html-branch repository on github.

### CODE REVIEW

**Comment by gchave77** [comment]
Amir, I thought that I submitted this review already. Please review.

**Review by ayunas — CHANGES_REQUESTED** [review]
@gchave77  You have notes.txt here on the html branch.  it should ONLY be on the text-branch.  Try to remove it from the branch.  Then flag me for review again.

**Comment by gchave77** [comment]
Amir, I deleted notes.txt locally from the html-branch and pushed to github. Thank you.

**Comment by gchave77** [comment]
Amir, 
I made the correction by deleting notes.txt locally from the html-branch and pushing to github.
Gracias,
gc

**Review by ayunas — APPROVED** [review]
@gchave77 Looks good ✅

**Pull request merged**
