### PR TITLE
move notes file from master to new branch

### PR DESCRIPTION
**Pull request by gchave77**

### CODE REVIEW

**Comment by gchave77** [comment]
merge text-branch

**Comment by ayunas** [comment]
@gchave77 Looks like this branch has merge conflicts that need to be resolved.  When you get a chance, please fix those issues.

**Review by ayunas — CHANGES_REQUESTED** [review]
@gchave77 This branch cannot be merged into master because there appears to be a merge conflict.  Try to fix the conflict.  and then request my review on this pull request again.

**Comment by gchave77** [comment]
Amir,
I believe I corrected the merge conflict.
image

**Comment by gchave77** [comment]
Amir,
I made the updates you requested and submitted new reviews to you in github.

Thank you,

Gabriel Chavez
619-886-8621 - mobile

**Review by ayunas — APPROVED** [review]
@gchave77 Looks good ✅

**Pull request merged**
